"""retirada_de_nome_em_secretaria

Revision ID: 1eb6ce8b3384
Revises: 96f3aa5c42a3
Create Date: 2026-04-07 10:58:43.265189

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1eb6ce8b3384'
down_revision = '96f3aa5c42a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secretarias', 'nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secretarias', sa.Column('nome', sa.VARCHAR(length=45), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
