"""criacao-tabela-ass-medicoesp

Revision ID: 4f490bc29357
Revises: ee80bd636c14
Create Date: 2026-04-11 14:46:13.743201

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4f490bc29357'
down_revision = 'ee80bd636c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('especialidades', 'status')
    op.drop_constraint(op.f('medicos_esp_id_fkey'), 'medicos', type_='foreignkey')
    op.drop_column('medicos', 'esp_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicos', sa.Column('esp_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('medicos_esp_id_fkey'), 'medicos', 'especialidades', ['esp_id'], ['esp_id'])
    op.add_column('especialidades', sa.Column('status', sa.VARCHAR(length=45), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
