"""init

Revision ID: d3b9d5394dd9
Revises: 
Create Date: 2026-03-31 17:44:50.339899

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd3b9d5394dd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('esp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=45), nullable=False),
    sa.Column('status', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('esp_id')
    )
    op.create_index(op.f('ix_areas_area_id'), 'areas', ['esp_id'], unique=False)
    op.create_table('doencas',
    sa.Column('doenca_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('doenca_id')
    )
    op.create_index(op.f('ix_doencas_doenca_id'), 'doencas', ['doenca_id'], unique=False)
    op.create_table('exames_clinicos',
    sa.Column('exame_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ist', sa.Boolean(), nullable=True),
    sa.Column('ist_numero', sa.Integer(), nullable=True),
    sa.Column('ist_hiv', sa.Boolean(), nullable=True),
    sa.Column('ist_diagnosticadas_num', sa.Integer(), nullable=True),
    sa.Column('diagnostico_cancer', sa.Boolean(), nullable=True),
    sa.Column('diagnostico_cin', sa.Boolean(), nullable=True),
    sa.Column('diagnostico_hpv', sa.Boolean(), nullable=True),
    sa.Column('diagnostico', sa.Boolean(), nullable=True),
    sa.Column('hinselmann', sa.Boolean(), nullable=True),
    sa.Column('schiller', sa.Boolean(), nullable=True),
    sa.Column('citologia', sa.Boolean(), nullable=True),
    sa.Column('biopsia', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('exame_id')
    )
    op.create_table('exames_imagem',
    sa.Column('exame_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=45), nullable=False),
    sa.Column('descricao', sa.String(length=45), nullable=True),
    sa.Column('link_imagem', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('exame_id')
    )
    op.create_index(op.f('ix_exames_imagem_exame_id'), 'exames_imagem', ['exame_id'], unique=False)
    op.create_table('pacientes',
    sa.Column('paciente_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('data_nascimento', sa.String(length=10), nullable=False),
    sa.Column('rg', sa.String(length=45), nullable=False),
    sa.Column('cpf', sa.String(length=45), nullable=False),
    sa.Column('data_cadastro', sa.String(length=45), nullable=False),
    sa.Column('endereco', sa.String(length=45), nullable=False),
    sa.Column('telefone', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('plano_saude', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('paciente_id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_pacientes_paciente_id'), 'pacientes', ['paciente_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('senha', sa.String(length=80), nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=False),
    sa.Column('telefone', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_usuario_id'), 'usuarios', ['usuario_id'], unique=False)
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index(op.f('ix_admin_admin_id'), 'admin', ['admin_id'], unique=False)
    op.create_table('medicamentos',
    sa.Column('medicamento_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.Column('exame_clinico_id', sa.Integer(), nullable=False),
    sa.Column('exame_imagem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exame_clinico_id'], ['exames_clinicos.exame_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exame_imagem_id'], ['exames_imagem.exame_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('medicamento_id')
    )
    op.create_index(op.f('ix_medicamentos_medicamento_id'), 'medicamentos', ['medicamento_id'], unique=False)
    op.create_table('medicos',
    sa.Column('medico_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('rg', sa.String(length=45), nullable=False),
    sa.Column('crm_numero', sa.String(length=45), nullable=False),
    sa.Column('crm_UF', sa.String(length=45), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('esp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['esp_id'], ['areas.esp_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('medico_id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('crm_numero')
    )
    op.create_index(op.f('ix_medicos_medico_id'), 'medicos', ['medico_id'], unique=False)
    op.create_table('resultados_exame_imagem_ia',
    sa.Column('resultado_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risco', sa.Float(), nullable=False),
    sa.Column('data_analise', sa.DateTime(), nullable=True),
    sa.Column('exame_imagem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exame_imagem_id'], ['exames_imagem.exame_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resultado_id')
    )
    op.create_index(op.f('ix_resultados_exame_imagem_ia_resultado_id'), 'resultados_exame_imagem_ia', ['resultado_id'], unique=False)
    op.create_table('secretarias',
    sa.Column('secretaria_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('rg', sa.String(length=15), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('secretaria_id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_secretarias_secretaria_id'), 'secretarias', ['secretaria_id'], unique=False)
    op.create_table('uploads_exame_imagem',
    sa.Column('upload_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=45), nullable=False),
    sa.Column('caminho_upload', sa.String(length=255), nullable=False),
    sa.Column('exame_imagem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exame_imagem_id'], ['exames_imagem.exame_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_index(op.f('ix_uploads_exame_imagem_upload_id'), 'uploads_exame_imagem', ['upload_id'], unique=False)
    op.create_table('consultas',
    sa.Column('consulta_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_consulta', sa.String(length=10), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('secretaria_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.medico_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.paciente_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['secretaria_id'], ['secretarias.secretaria_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consulta_id')
    )
    op.create_index(op.f('ix_consultas_consulta_id'), 'consultas', ['consulta_id'], unique=False)
    op.create_table('prontuarios',
    sa.Column('prontuario_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consulta', sa.Integer(), nullable=False),
    sa.Column('exame_clinico', sa.Integer(), nullable=False),
    sa.Column('exame_imagem', sa.Integer(), nullable=False),
    sa.Column('medicamento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['consulta'], ['consultas.consulta_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exame_clinico'], ['exames_clinicos.exame_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exame_imagem'], ['exames_imagem.exame_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicamento'], ['medicamentos.medicamento_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prontuario_id')
    )
    op.create_index(op.f('ix_prontuarios_prontuario_id'), 'prontuarios', ['prontuario_id'], unique=False)
    op.create_table('doenca_prontuario',
    sa.Column('doenca_prontuario_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doenca_id', sa.Integer(), nullable=False),
    sa.Column('prontuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doenca_id'], ['doencas.doenca_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prontuario_id'], ['prontuarios.prontuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doenca_prontuario_id')
    )
    op.create_index(op.f('ix_doenca_prontuario_doenca_prontuario_id'), 'doenca_prontuario', ['doenca_prontuario_id'], unique=False)
    op.create_table('habitos_vida',
    sa.Column('habitos_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_parceiros', sa.Integer(), nullable=True),
    sa.Column('primeira_relacao', sa.Integer(), nullable=True),
    sa.Column('numero_gravidez', sa.Integer(), nullable=True),
    sa.Column('fuma', sa.Boolean(), nullable=True),
    sa.Column('fuma_anos', sa.Integer(), nullable=True),
    sa.Column('contraceptivo_hormonal', sa.Boolean(), nullable=True),
    sa.Column('contraceptivo_hormonal_anos', sa.Integer(), nullable=True),
    sa.Column('diu', sa.Boolean(), nullable=True),
    sa.Column('diu_anos', sa.Integer(), nullable=True),
    sa.Column('prontuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prontuario_id'], ['prontuarios.prontuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('habitos_id')
    )
    op.create_index(op.f('ix_habitos_vida_habitos_id'), 'habitos_vida', ['habitos_id'], unique=False)
    op.create_table('historicos',
    sa.Column('historico_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modificacao', sa.String(length=45), nullable=False),
    sa.Column('data_modificacao', sa.String(length=20), nullable=False),
    sa.Column('prontuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prontuario_id'], ['prontuarios.prontuario_id'], ),
    sa.PrimaryKeyConstraint('historico_id')
    )
    op.create_index(op.f('ix_historicos_historico_id'), 'historicos', ['historico_id'], unique=False)
    op.create_table('resultado_analise_habito',
    sa.Column('resultado_analise_hb_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risco', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('habito_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['habito_id'], ['habitos_vida.habitos_id'], ),
    sa.PrimaryKeyConstraint('resultado_analise_hb_id')
    )
    op.create_index(op.f('ix_resultado_analise_habito_resultado_analise_hb_id'), 'resultado_analise_habito', ['resultado_analise_hb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultado_analise_habito_resultado_analise_hb_id'), table_name='resultado_analise_habito')
    op.drop_table('resultado_analise_habito')
    op.drop_index(op.f('ix_historicos_historico_id'), table_name='historicos')
    op.drop_table('historicos')
    op.drop_index(op.f('ix_habitos_vida_habitos_id'), table_name='habitos_vida')
    op.drop_table('habitos_vida')
    op.drop_index(op.f('ix_doenca_prontuario_doenca_prontuario_id'), table_name='doenca_prontuario')
    op.drop_table('doenca_prontuario')
    op.drop_index(op.f('ix_prontuarios_prontuario_id'), table_name='prontuarios')
    op.drop_table('prontuarios')
    op.drop_index(op.f('ix_consultas_consulta_id'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_uploads_exame_imagem_upload_id'), table_name='uploads_exame_imagem')
    op.drop_table('uploads_exame_imagem')
    op.drop_index(op.f('ix_secretarias_secretaria_id'), table_name='secretarias')
    op.drop_table('secretarias')
    op.drop_index(op.f('ix_resultados_exame_imagem_ia_resultado_id'), table_name='resultados_exame_imagem_ia')
    op.drop_table('resultados_exame_imagem_ia')
    op.drop_index(op.f('ix_medicos_medico_id'), table_name='medicos')
    op.drop_table('medicos')
    op.drop_index(op.f('ix_medicamentos_medicamento_id'), table_name='medicamentos')
    op.drop_table('medicamentos')
    op.drop_index(op.f('ix_admin_admin_id'), table_name='admin')
    op.drop_table('admin')
    op.drop_index(op.f('ix_usuarios_usuario_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_pacientes_paciente_id'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_exames_imagem_exame_id'), table_name='exames_imagem')
    op.drop_table('exames_imagem')
    op.drop_table('exames_clinicos')
    op.drop_index(op.f('ix_doencas_doenca_id'), table_name='doencas')
    op.drop_table('doencas')
    op.drop_index(op.f('ix_areas_area_id'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
