"""table-associ-medicoesp

Revision ID: e60a0e5dcb1c
Revises: 4f490bc29357
Create Date: 2026-04-12 01:42:47.218381

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e60a0e5dcb1c'
down_revision = '4f490bc29357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medico_especialidades',
    sa.Column('med_esp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('esp_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ESPECIALISTA', 'RESIDENTE', 'POS_GRADUANDO', 'ESPECIALIZACAO', 'GENERALISTA', name='statusesp'), nullable=True),
    sa.ForeignKeyConstraint(['esp_id'], ['especialidades.esp_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.medico_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('med_esp_id')
    )
    op.create_index(op.f('ix_medico_especialidades_med_esp_id'), 'medico_especialidades', ['med_esp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medico_especialidades_med_esp_id'), table_name='medico_especialidades')
    op.drop_table('medico_especialidades')
    # ### end Alembic commands ###
