"""remocao-nome-medico

Revision ID: ee80bd636c14
Revises: 7dca82a41257
Create Date: 2026-04-11 13:47:17.766167

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ee80bd636c14'
down_revision = '7dca82a41257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicos', 'nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicos', sa.Column('nome', sa.VARCHAR(length=45), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
