"""oncascade-retirado-de-medicos_area_id

Revision ID: fb1f83cf26ab
Revises: 1eb6ce8b3384
Create Date: 2026-04-08 23:41:00.281724

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fb1f83cf26ab'
down_revision = '1eb6ce8b3384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('medicos_area_id_fkey'), 'medicos', type_='foreignkey')
    op.create_foreign_key(None, 'medicos', 'areas', ['esp_id'], ['esp_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medicos', type_='foreignkey')
    op.create_foreign_key(op.f('medicos_area_id_fkey'), 'medicos', 'areas', ['esp_id'], ['esp_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
